### ISSUE TITLE
Ubuntu Build Issue python-cryptography

### ISSUE THREAD

**Issue by ChristopherDavenport** [AnsibleCheck/ansiblecheck#28]
[Example Failed Build](https://travis-ci.org/AnsibleCheck/ansiblecheck/jobs/278776680)

```
The following packages have unmet dependencies:
 ansible : Depends: python-cryptography but it is not installable
```

**Comment by lcaflc** [comment]
Hi,
python-cryptography is a new depends for ansible version 2.4+ on the debian package. However this package is not available for ubuntu 12.04 precise :angry: 

possobilities:
 - report the issue to ansible packaging team
 - install ansible using pip command on Ubuntu precise
 - drop precise support

**Comment by trinitronx** [comment]
Looks like they fixed this dependency issue in: ansible/ansible#26726

However, I'm not sure which repo these debs are pushed to.. still seeing issues on Ubuntu <= `12.04` with [Ansible PPA][1] as installed by [`omnibus-ansible`][2]

[1]: https://launchpad.net/~ansible/+archive/ubuntu/ansible
[2]: https://github.com/neillturner/omnibus-ansible

**Comment by Firefishy** [comment]
@lcaflc see my linked PR. Broken ```python-cryptography``` dependency fix.

**Comment by Firefishy** [comment]
Fix coming in PPA release of Ansible 2.4.4

**Comment by Firefishy** [comment]
@lcaflc @ChristopherDavenport I fixed the upstream PPA repos / code.

**Comment by ChristopherDavenport** [comment]
What do I need to help with this. I'm not around on this as much anymore.

**Comment by lcaflc** [comment]
This is an older release no longuer supported.
