### ISSUE TITLE
Second Maintainer

### ISSUE THREAD

**Issue by ChristopherDavenport** [AnsibleCheck/ansiblecheck#31]
I am having less and less time for this project, but this seems to be actively in use. Is anyone interested in helping maintain?

**Comment by lcaflc** [comment]
I @ChristopherDavenport 

I have a few things to do curently on ansible so I can help you on my spare time also. Just add Ubuntu Bionic support.

Thanks.

**Comment by ChristopherDavenport** [comment]
Do you have a docker alias that I can add to maintaining the docker org?

**Comment by lcaflc** [comment]
It's also lcaflc https://hub.docker.com/u/lcaflc/

Thanks.

**Comment by ChristopherDavenport** [comment]
You should be all set!

**Comment by Yajo** [comment]
I can co-maintain if you want. My Hub profile is https://hub.docker.com/u/yajo/
