### ISSUE TITLE
Missing Tags on Docker Hub

### ISSUE THREAD

**Issue by franklinkim** [AnsibleCheck/ansiblecheck#34]
Some Tag like `ubuntu-18.04` seem to be missing on [Docker Hub](https://hub.docker.com/r/ansiblecheck/ansiblecheck/tags)

**Comment by lcaflc** [comment]
Thanks for your report.

@ChristopherDavenport  can you check that or give me access to build settings on docker hub. Maybe because of newly updated docker hub, I cannot see and neither change the build settings.

Thanks.

**Comment by ChristopherDavenport** [comment]
@lcaflc  You are added on the ansiblecheck organization. I'm not sure why you would not have access presently.

**Comment by lcaflc** [comment]
Thanks @ChristopherDavenport it's ok now.
I'm adding the ubuntu 18.04 build

**Comment by lcaflc** [comment]
Thanks @franklinkim for the report. the ubuntu 18.04 bionic builds are now available on the docker hub.
